disabled_rules:
  - trailing_whitespace
  - vertical_whitespace

opt_in_rules:
  - empty_count
  - missing_docs

excluded:
  - reference
  - AINewsReporter/Tests
  - AINewsReporterTests
  - AINewsReporterUITests

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 250
  error: 400

file_length:
  warning: 400
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20 